name: timezone
version: 0.3.1
author: Boris Kaul <localvoid@gmail.com>
description: Time zone database and time zone aware DateTime.
homepage: https://github.com/localvoid/timezone
environment:
  sdk: '>=1.9.0'
dependencies:
  path: '^1.3.0'
dev_dependencies:
  args: any
  browser: any
  glob: any
  logging: any
  test: '^0.12.0'
