name: timezone
version: 0.1.0
author: Boris Kaul <localvoid@gmail.com>
description: Library to convert DateTimes between Time Zones.
homepage: https://github.com/localvoid/timezone
environment:
  sdk: '>=1.6.0'
dependencies:
  collection: '>=1.0.0 <2.0.0'
  tuple: '>=0.1.0 <=1.0.0'
dev_dependencies:
  args: any
  glob: any
  logging: any
  path: any
  unittest: any
