name: timezone
version: 0.3.1
author: Boris Kaul <localvoid@gmail.com>
description: Time zone database and time zone aware DateTime.
homepage: https://github.com/localvoid/timezone
environment:
  sdk: '>=1.9.0'
dependencies:
  tuple: '>=0.1.0 <0.2.0'
  path: '>=1.3.0 <1.4.0'
dev_dependencies:
  args: any
  browser: any
  glob: any
  logging: any
  unittest: any
