name: timezone
version: 0.2.4
author: Boris Kaul <localvoid@gmail.com>
description: Time zone database and time zone aware DateTime.
homepage: https://github.com/localvoid/timezone
environment:
  sdk: '>=1.8.0'
dependencies:
  tuple: '>=0.1.0 <0.2.0'
  args: '>=0.12.1 <0.13.0'
  path: '>=1.3.0 <1.4.0'
dev_dependencies:
  browser: any
  glob: any
  logging: any
  unittest: any
